### ISSUE TITLE
command line options in addition to environmental variables

### ISSUE THREAD

**Issue by AndySchroder** [estkme-group/lpac#102]
I'd like to suggest that for each option, you have the following:

1. A default value if not set otherwise (some options like `AT_DEVICE` and `INTERFACE_SELECT_ENV`, I think maybe there should be no default and it should be explicitly required to be passed).
2. An environmental variable that overrides the default.
3. A command line option that overrides the default value and the environmental variable.

I find it a bit cumbersome to have to set environmental variables for everything. The above is what most applications do. People are used to command line options and something like `lpac -h` to tell them what those options are.

**Comment by damonto** [comment]
not planned.

**Comment by AndySchroder** [comment]
also, it's much more cumbersome to call lpac from other applications like python using the environmental variable approach vs command line options.

**Comment by damonto** [comment]
The original version of lpac did not have a default value of environment variables, but we received a lot of user feedback that they did not know how to correctly set environment variables on Linux, Windows, and macOS. Most of our users are not familiar with the command line, so we decided to add a default value to env. This way, users can use lpac without having to set up environment variables manually. We hope this change will make it easier for users to get started with lpac.

We do not have plans to implement a command line option at the moment. If you would like to implement this feature, feel free to submit a PR.

**Comment by bam80** [comment]
> We do not have plans to implement a command line option at the moment.

@damonto please reopen this issue, it's still actual

**Comment by estkme** [comment]
Because lpac uses a single point of entry (similar to busybox) dynamic driver backend, there is currently no good pattern for different drivers to register different command line parameters (the same is true for gstramer when processing plug-ins). If there is no better solution to PR to the lpac project, I am afraid this issue will remain open **forever**.


So I think closing this issue is a good choice. Again, we welcome and appreciate PRs that can effectively and reasonably solve this problem.
